param(
  [Parameter(Mandatory=$true)][string]$JobsJson,
  [Parameter(Mandatory=$true)][string]$OutputFolder,
  [Parameter(Mandatory=$true)][int]$JobIndex
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot;$jobsPath=[IO.Path]::GetFullPath($JobsJson);$jobsRoot=Split-Path -Parent $jobsPath;$document=Get-Content -Raw $jobsPath|ConvertFrom-Json
if($document.schema_version -ne 'creo-render-jobs/v3'){throw 'Pixel V3 requires formal v3 jobs.'};$job=@($document.jobs)[$JobIndex];if($null -eq $job){throw "No job at index $JobIndex"}
$manifest=Get-Content -Raw (Join-Path $jobsRoot $document.authoritative_assembly_manifest)|ConvertFrom-Json;$source=Join-Path $root ('零件图\'+$manifest.assembly_file);$hash=(Get-FileHash $source -Algorithm SHA256).Hash.ToLowerInvariant();if($hash -ne $manifest.assembly_sha256.ToLowerInvariant()){throw 'Authoritative assembly hash mismatch.'}
$out=[IO.Path]::GetFullPath($OutputFolder);if(Test-Path $out){throw "Output exists: $out"};New-Item -ItemType Directory $out|Out-Null;& (Join-Path $PSScriptRoot 'test_license_binding.ps1') -LicenseFile 'C:\ProgramData\PTC\Licensing\BK130602EDUNIVERSITYED_license.dat'
$stage=Join-Path $out 'models';Copy-Item (Join-Path $root '零件图') $stage -Recurse;Copy-Item (Join-Path $PSScriptRoot 'isolated_config.pro') (Join-Path $stage 'config.pro') -Force;$assembly=Join-Path $stage $manifest.assembly_file
$camera=Get-Content -Raw (Join-Path $jobsRoot $job.camera_contract_file)|ConvertFrom-Json;if($camera.selected.id -notin @('fixed_123','fixed_456')){throw 'Invalid fixed camera'};$fmt={param($v)(@($v|%{([double]$_).ToString('G17',[cultureinfo]::InvariantCulture)})-join ':')};$spec='ABS:'+(& $fmt $camera.selected.position_direction_root)+',UP:'+(& $fmt $camera.selected.up_reference_root)+',ZOOM:'+([double]$camera.framing.zoom).ToString('G17',[cultureinfo]::InvariantCulture)+',CENTER,PAN:'+([double]$camera.framing.pan[0]).ToString('G17',[cultureinfo]::InvariantCulture)+':'+([double]$camera.framing.pan[1]).ToString('G17',[cultureinfo]::InvariantCulture)
$expected=@($job.stage_visibility.completed_occurrences)+@($job.moving_occurrences)+@($job.receiver_occurrences)+@($job.stage_visibility.required_context_occurrences)|?{$_}|Sort-Object -Unique;if((@($job.visible_occurrences|Sort-Object -Unique)-join ';') -ne ($expected-join ';')){throw 'Forward visibility contract mismatch'}
$base=Join-Path $out ($job.job_id+'.base.jpg');$cal=Join-Path $out ($job.job_id+'.calibration.jpg');$audit=Join-Path $out ($job.job_id+'.arrow.json');$v=@($job.translation.vector)
$row={param($file,$native) (@($file,(@($job.moving_occurrences)-join ';'),$v[0],$v[1],$v[2],(@($job.visible_occurrences)-join ';'),$spec,$audit,$native) -join "`t") }
$tsv=Join-Path $out 'pixel-v3.tsv';[IO.File]::WriteAllLines($tsv,@((& $row $cal 'true'),(& $row $base 'false')),[Text.UTF8Encoding]::new($false))
$ptc='C:\Program Files\PTC\Creo 13.4.0.0';$common=Join-Path $ptc 'Common Files';$native=Join-Path $common 'x86e_win64\lib';$env:PATH="$native;$(Join-Path $ptc 'Parametric\bin');$env:PATH";$env:PRO_DIRECTORY=Join-Path $ptc 'Parametric';$env:CREO_COMMON_FILES=$common;$env:PRO_COMM_MSG_EXE=Join-Path $common 'x86e_win64\obj\pro_comm_msg.exe';$env:PTC_D_LICENSE_FILE='C:\ProgramData\PTC\Licensing\BK130602EDUNIVERSITYED_license.dat';$env:CREO_APP='PMA';$env:CREOPMA_FEATURE_NAME='CREOPMA_StudentP6 ()';$cp=(Join-Path $PSScriptRoot 'build')+';'+(Join-Path $common 'text\java\pfcasync.jar')+';'+(Join-Path $common 'text\java\otk.jar')
Push-Location $stage;try{& (Get-Command java).Source '--enable-native-access=ALL-UNNAMED' ('-Djava.library.path='+$native) '-cp' $cp 'PixelArrowBaseBatchV3' ('"'+(Join-Path $ptc 'Parametric\bin\parametric.bat')+'"') $assembly $tsv 2>&1|Tee-Object (Join-Path $out 'pixel-v3-jlink.log');if($LASTEXITCODE -ne 0){throw 'PixelArrowBaseBatchV3 failed'}}finally{Pop-Location}
& (Join-Path $PSScriptRoot 'compose_pixel_arrows_v3_runner.ps1') -BaseJpeg $base -CalibrationJpeg $cal -OutputJpeg (Join-Path $out ($job.job_id+'.jpg')) -ExpectedArrowCount @($job.moving_occurrences).Count
